dialect: sqlite
host: localhost
port: 3306
schema: minecraft
username: root
password: password
# Valid dialects:
# sqlite, mysql, mariadb
# TODO Support postgres
# TODO Support optional caching using redis/memcached
# TODO Support h2 AND sqlite