name: IDLogger
version: 1.0
description: System for logging a player's current name and UUID
author: smeef
website: https://github.com/arif-banai
api-version: 1.15

main: me.arifbanai.idLogger.IDLogger